development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://sbirojdmxcfjdo:XvnZ_QqNeupZBVMQrVMyETBt73@ec2-54-83-44-117.compute-1.amazonaws.com:5432/ddmget63lht726

